Failure # 1 (occurred at 2024-01-02_15-22-05)
Traceback (most recent call last):
  File "D:\envs\marllib\lib\site-packages\ray\tune\trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "D:\envs\marllib\lib\site-packages\ray\tune\ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "D:\envs\marllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "D:\envs\marllib\lib\site-packages\ray\worker.py", line 1627, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

